In [2]:
import numpy as np

In [3]:
ar1=np.array([1,2,3])
ar1=np.array([100,'raju',23,99])

In [4]:
print(type(ar1))

<class 'numpy.ndarray'>


In [5]:
print(np.array([1,2,3]))

[1 2 3]


In [6]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [7]:
print(np.zeros((3,5),dtype=int))#3 rows 5 columns

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [8]:
print(np.zeros((3,5))) #float

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
print(np.full((3,3),(5)))#3x3 array with value 5

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [11]:
print(np.eye(3))#identity matrix 1 diagonal matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#linspace(start,end,number of items)
print(np.linspace(5,50,8))# will create 8 equal parts b/n 5 to 50(float)

[ 5.         11.42857143 17.85714286 24.28571429 30.71428571 37.14285714
 43.57142857 50.        ]


In [13]:
#np.arange(start,stop,step)
print(np.arange(10,30,2))  #(int)it creates an array from 10 to 30 with step size 2


[10 12 14 16 18 20 22 24 26 28]


In [14]:
# rand  = 0-1
print(np.random.rand(2,3,200))# gives values b/n 0-1

[[[0.04316938 0.39534567 0.20265873 ... 0.41355348 0.45781507 0.14381365]
  [0.41918782 0.15639507 0.47895403 ... 0.42750884 0.21442592 0.98226776]
  [0.27860232 0.45319262 0.82220812 ... 0.71684349 0.26402859 0.79640865]]

 [[0.92282687 0.00975536 0.62707965 ... 0.66929065 0.10816162 0.57053406]
  [0.52572757 0.63591505 0.53054943 ... 0.3720616  0.17599411 0.7068824 ]
  [0.06451659 0.62167602 0.87533844 ... 0.43007081 0.26422664 0.57820342]]]


In [15]:
print(np.random.rand(5,5)*75) # 5x5 matrix with random values b/n 0-75


[[ 1.88102803 26.50820512 69.82258812 37.81262195 62.26132364]
 [33.6819476  50.33274713 24.57665774  6.60623861 44.64409027]
 [ 7.82693209 35.60913434 24.78866787 44.65901012 19.86065091]
 [38.40952697 37.00216749 20.90484549 70.78291028 70.51338697]
 [35.45605406 12.54181798 70.12454529 59.43821979 57.86850915]]


In [16]:
print(np.random.choice([1,2,3,4,5,6])) #picks a random number


6


In [17]:
print(np.random.choice([1,2,3,4],size=(3,3)))


[[1 3 3]
 [4 2 3]
 [1 4 4]]


In [18]:
#"randint"fit gives random values between them , no float vlaues
print(np.random.randint(15,size=(5,5)))# will create array with random ints  b/n 0-14


[[ 6 14  2 14  3]
 [10  2  5  9  1]
 [ 6  5  2  1  3]
 [ 8  3  1 11  0]
 [14  2 10 13  9]]


In [19]:
print(np.random.randint(15,25,size=(4,3)))

[[17 19 20]
 [21 24 17]
 [16 23 24]
 [20 23 17]]


In [20]:
print(np.random.randint(1,100,20))

[59 31 29 50 72 16 26 88 79 21 88 30 67 53 55 13 91 33 50 77]


In [21]:
# values are between them only with float values
print(np.random.uniform(0.9,30.5,50))


[ 3.55080703 25.17291037 20.53713242  8.4144749  22.63808824  3.49825098
 12.71744348  8.48321859 13.67050698 17.35389559  7.38250247 12.10672444
 29.48132586  8.76971226 10.3761973  29.26840378 18.55878103 12.8716689
 19.67985917 19.85858484 14.08073873 20.1414587   3.52172168 15.90222866
 14.74406597 27.42621173 27.9946695  21.54757834  9.93319213  1.71200342
 19.27764705 29.93440442  2.4153404  15.79349313 18.00823659  6.79706077
 26.99805916  0.99074795 22.19165047 21.6677703  23.05702413  7.72745567
 16.47469032 16.19762358  5.04252743 23.79528721  3.40493052 19.83715266
 22.38271186 21.79117861]


In [22]:
#  normal distributed data  i.e graph like  ----^----
print(np.random.randn(10)) 

[ 2.2844254   0.31179416  2.89178532  0.50698601 -2.29928004  0.76328737
  0.87764508 -0.88990429 -0.23539942  0.99830432]


In [23]:
c=np.array([40,50,60])
d=np.array([70,80,66])

In [24]:
print(c+d)

[110 130 126]


In [25]:
print(c.shape)

(3,)


In [26]:
print(c*d)

[2800 4000 3960]


In [27]:
print(np.max(c))

60


In [28]:
print(np.sin(c))

[ 0.74511316 -0.26237485 -0.30481062]


In [29]:
print(np.tan(c))

[-1.11721493 -0.27190061  0.32004039]


In [30]:
print(np.mean(c))

50.0


In [31]:
print(np.median(d))

70.0


In [32]:
print(np.exp(c))

[2.35385267e+17 5.18470553e+21 1.14200739e+26]


In [33]:
print(np.sum(c))

150


# inspecting properties

In [34]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8],[9,8,7],[4,3,2],[2,3,6]])# float>int

In [35]:
print(arr.size) # no of elements in the array


18


In [36]:
print(arr.shape) # give the type of matrix


(6, 3)


In [37]:
print("the data type of the array:",arr.dtype)#data type


the data type of the array: int32


In [38]:
print("convertion to list:",arr.tolist())

convertion to list: [[1, 2, 3], [4, 5, 6], [6, 7, 8], [9, 8, 7], [4, 3, 2], [2, 3, 6]]


# copying/sorting/reshaping

In [39]:
arr=np.array([[2,3,4],[6,7,8]])
print(arr)

[[2 3 4]
 [6 7 8]]


In [40]:
print("Address of arr:",id(arr))

Address of arr: 2377102151728


In [41]:
arr1=arr

In [42]:
print("Address of arr:",id(arr1))

Address of arr: 2377102151728


In [43]:
#the address is same

In [44]:
arr2=np.copy(arr)

In [45]:
print("Address of arr2:",id(arr2))

Address of arr2: 2377102153168


# copy method implementation of integer

In [46]:
a=1911
print("Address of a:",id(a))

Address of a: 2377101950640


In [47]:
b=a
print("Address of b:",id(b))

Address of b: 2377101950640


In [48]:
c=np.copy(a)
print("Address of c:",id(c))

Address of c: 2377102155280


In [49]:
arr=np.array([ 3,5,7,8,9])
print(arr)

[3 5 7 8 9]


In [50]:
arr=np.array(["shiva",56,78.8,98,"naveen"]) #sees first character


In [51]:
print(arr)

['shiva' '56' '78.8' '98' 'naveen']


In [52]:
print(np.sort(arr))

['56' '78.8' '98' 'naveen' 'shiva']


In [53]:
arr=np.array([[3,4,5],[6,7,8]])

In [54]:
print(np.sort(arr))

[[3 4 5]
 [6 7 8]]


In [55]:
arr=np.array([[4,5,12],[6,8,78]])
print(arr)

[[ 4  5 12]
 [ 6  8 78]]


In [56]:
print(arr.flatten()) #will convert 2D array to 1D

[ 4  5 12  6  8 78]


In [57]:
print(arr.T) #transpose

[[ 4  6]
 [ 5  8]
 [12 78]]


In [58]:
arr=np.array([[9,12,5],[67,5,9],[6,8,12],[1,4,6]])
print(arr.reshape(3,4)) 
#will reshape the array into 3x4 array  as it has 12 variables


[[ 9 12  5 67]
 [ 5  9  6  8]
 [12  1  4  6]]


In [59]:
print(np.resize(arr,(5,5)))
# will change array shape to 5x5 

[[ 9 12  5 67  5]
 [ 9  6  8 12  1]
 [ 4  6  9 12  5]
 [67  5  9  6  8]
 [12  1  4  6  9]]


In [60]:
arr=np.array([[1,2,3,4],[3,4,5,6],[4,5,6,7],[6,7,8,9]])
print(arr)

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]
 [6 7 8 9]]


In [61]:
arr1=np.append(arr,[10,20,30,40])

In [62]:
print(arr1)
#print(arr1) #it wont print in matrix form use reshape

[ 1  2  3  4  3  4  5  6  4  5  6  7  6  7  8  9 10 20 30 40]


In [63]:
arr1=arr1.reshape(5,4)
print(arr1)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [10 20 30 40]]


In [64]:
arr1=np.insert(arr,6,(12,13,14,15))
#matrix will add by  6th position onwards
arr1=arr1.reshape(5,4)
print(arr1)

[[ 1  2  3  4]
 [ 3  4 12 13]
 [14 15  5  6]
 [ 4  5  6  7]
 [ 6  7  8  9]]


In [65]:
print(np.delete(arr,1,axis=0))

[[1 2 3 4]
 [4 5 6 7]
 [6 7 8 9]]


In [66]:
print(np.delete(arr,2,axis=1))

[[1 2 4]
 [3 4 6]
 [4 5 7]
 [6 7 9]]


# concatenate

In [67]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[100,200,300,400,500],[34,56,43,21,76]])
arr1=np.array([[12,13,14,15,16],[21,22,23,24,25],[31,32,33,34,35],[56,57,58,59,60]])
arr2=np.array([[5,6,7,8],[3,4,5,6],[1,2,3,4],[7,8,9,90]])
print(arr)

[[  1   2   3   4   5]
 [  4   5   6   7   8]
 [100 200 300 400 500]
 [ 34  56  43  21  76]]


In [68]:
print(arr1)


[[12 13 14 15 16]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [56 57 58 59 60]]


In [69]:
print(arr2)

[[ 5  6  7  8]
 [ 3  4  5  6]
 [ 1  2  3  4]
 [ 7  8  9 90]]


In [70]:
print(np.concatenate((arr,arr1),axis=0)) 
# it will add rows to the arr


[[  1   2   3   4   5]
 [  4   5   6   7   8]
 [100 200 300 400 500]
 [ 34  56  43  21  76]
 [ 12  13  14  15  16]
 [ 21  22  23  24  25]
 [ 31  32  33  34  35]
 [ 56  57  58  59  60]]


In [71]:
print(np.concatenate((arr,arr1),axis=1))
#it will add columns to arr

[[  1   2   3   4   5  12  13  14  15  16]
 [  4   5   6   7   8  21  22  23  24  25]
 [100 200 300 400 500  31  32  33  34  35]
 [ 34  56  43  21  76  56  57  58  59  60]]


In [72]:
print(np.split(arr2,2)) 
# will split array to sub array based on rows


[array([[5, 6, 7, 8],
       [3, 4, 5, 6]]), array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 90]])]


In [74]:
arr1=np.array([[12,13,14,15],[21,22,24,25],[31,32,34,35],[56,58,59,60]])
print(np.hsplit(arr1,2)) 
#will split to sub array horizotally i.e columns


[array([[12, 13],
       [21, 22],
       [31, 32],
       [56, 58]]), array([[14, 15],
       [24, 25],
       [34, 35],
       [59, 60]])]


In [75]:
print(np.vsplit(arr1,2))
# vertical 

[array([[12, 13, 14, 15],
       [21, 22, 24, 25]]), array([[31, 32, 34, 35],
       [56, 58, 59, 60]])]


# indexing/slicing/subsetting

In [77]:
arr=np.array([10,11,2,13,14])
arr1=np.array([[12,14,5,78,7],[5,7,66,4,87]])

print(arr[4])  # will give the number based on index


14


In [78]:
print(arr1[1,4])# will give the elements of 2d array


87


In [79]:
arr[1]=9
print(arr)

[10  9  2 13 14]


In [80]:
arr1[1,4]=10
print(arr1)

[[12 14  5 78  7]
 [ 5  7 66  4 10]]


In [81]:
print(arr[:3]) # excluding 3 it gives the all values
#will give the elements in array with positions


[10  9  2]


In [82]:
print(arr1[0:2,0:1]) 
# will give the elements on rows 0,1,2


[[12]
 [ 5]]


In [83]:
print(arr1[:1])

[[12 14  5 78  7]]


In [84]:
print(arr1[:,:2])

[[12 14]
 [ 5  7]]


In [85]:
print(arr<5)# return an array with boolean value


[False False  True False False]


In [86]:
print((arr>3)&(arr<5))

[False False False False False]


In [87]:
print(arr1<5)

[[False False False False False]
 [False False False  True False]]


# scalar math

In [88]:
arr=np.array([10,11,12,13,14])
arr1=np.array([[10,11,12,13,14],[21,22,23,24,25]])


In [89]:
print(np.add(arr,2)) # will add 2 to each array element


[12 13 14 15 16]


In [90]:
print(np.add(arr1,2))  #will add 2 to each array element


[[12 13 14 15 16]
 [23 24 25 26 27]]


In [91]:
print(np.subtract(arr,5))  #will sub 5 to each array element

[5 6 7 8 9]


In [92]:
print(np.multiply(arr,5))  #will mul 5 to each  and every  element


[50 55 60 65 70]


In [93]:
print(np.divide(arr1,4))


[[2.5  2.75 3.   3.25 3.5 ]
 [5.25 5.5  5.75 6.   6.25]]


In [94]:
print(np.power(arr,2))  


[100 121 144 169 196]


# vector math

In [95]:
arr=np.array([[1.1,2.8,3.6,4],[5.2,6.5,7.8,8.9]])

arr1=np.array([[9,10,11,12],[13,14,15,16]])
              
arr2=np.array([[9,10,11,12],[13,14,15,16]])

In [96]:
print(np.array_equal(arr2,arr1))


True


In [97]:
print(np.sqrt(arr1))

[[3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]


In [98]:
print(np.sin(arr1))  # radians values

[[ 0.41211849 -0.54402111 -0.99999021 -0.53657292]
 [ 0.42016704  0.99060736  0.65028784 -0.28790332]]


In [99]:
print(np.log(arr1))

[[2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]


In [100]:
print(np.ceil(arr))

[[2. 3. 4. 4.]
 [6. 7. 8. 9.]]


In [101]:
print(np.floor(arr))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [102]:
print(np.round(arr1))

[[ 9 10 11 12]
 [13 14 15 16]]


In [103]:
print(np.round(arr)) #round figure

[[1. 3. 4. 4.]
 [5. 6. 8. 9.]]


In [104]:
arr=np.array([[9,10,11,12],[13,14,15,6]])
              
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [105]:
print(np.mean(arr1,axis=0))

[3. 4. 5. 6.]


In [106]:
print(np.mean(arr1))

4.5


In [107]:
print(np.mean(arr1,axis=1))

[2.5 6.5]


In [108]:
print(arr1.min())

1


In [109]:
print(arr.max())

15


In [110]:
print(arr.max(axis=1))

[12 15]


In [111]:
arr=np.array([[3,4],[5,6]])
print(np.var(arr))  #variance

1.25


In [112]:
print(np.std(arr,axis=1))

[0.5 0.5]
